-- AlterTable
ALTER TABLE "Ill" ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "type" DROP DEFAULT,
ALTER COLUMN "about" DROP NOT NULL,
ALTER COLUMN "about" DROP DEFAULT,
ALTER COLUMN "info" DROP NOT NULL,
ALTER COLUMN "info" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Survey" ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "type" DROP DEFAULT,
ALTER COLUMN "about" DROP NOT NULL,
ALTER COLUMN "about" DROP DEFAULT,
ALTER COLUMN "info" DROP NOT NULL,
ALTER COLUMN "info" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "fullName" TEXT,
ADD COLUMN     "email" TEXT,
ADD COLUMN     "phone" TEXT,
ALTER COLUMN "pwd" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Vaccine" ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "type" DROP DEFAULT,
ALTER COLUMN "about" DROP NOT NULL,
ALTER COLUMN "about" DROP DEFAULT,
ALTER COLUMN "info" DROP NOT NULL,
ALTER COLUMN "info" DROP DEFAULT;
